### ISSUE TITLE
Technical overview of active learning applications

### ISSUE THREAD

**Issue by andy-sweet** [chanzuckerberg/idetik#1]
The goal of this work is to produce a high level technical design document that describes the rough components and architecture needed to implement an application that supports at least one workflow of active learning with cell tracking data.

The work will be collaborative with Jordão at the SF Biohub, using one or more of the existing software workflows he has put together using existing software tools like napari.

This document should describe how such an application would use other components that we plan to work on (e.g. visualization), CZI plans to work on (e.g. AI model serving), and already exist.

This should be complete in less than a week. We do not need detailed technical specifications at this point. We should mostly hold off visual designs. The goal should instead frame future technical design work.

# References

- [Image-based active learning sample schema](https://docs.google.com/document/d/1iQayKCsgnfN7kkguhZRRoE-z47jU32G15Ae6vVG5FEc/edit#heading=h.jksdvaj0d1ke)
- [Web-viewer library technical overview](https://docs.google.com/document/d/1aw0TVdweqjKjqZv9XHW-lC5K3RRSMezw_Ue2V23uKO0/edit)
- [Active learning mock server repo](https://github.com/royerlab/active-learning-mock-server)

**Comment by andy-sweet** [comment]
While cell tracking is one of the key domains/workflows we want to capture here, this overview also attempts to capture the overlap between that and some of the similar CryoET workflows.

**Comment by aganders3** [comment]
Just adding a reference to the document:
[Active learning: application examples
](https://docs.google.com/document/d/1OmqpMBjy4bkt9rVvzrqr0eaXD08votB4BJnWb11Nm4E/edit#heading=h.7y907dtzbmew)

**Comment by andy-sweet** [comment]
I think the goals of the issue were accomplished in [application examples document](https://docs.google.com/document/d/1OmqpMBjy4bkt9rVvzrqr0eaXD08votB4BJnWb11Nm4E/edit#heading=h.7y907dtzbmew) and I don't plan to work any more on this specific issue, so I'm closing.
