### ISSUE TITLE
Final task is re-loaded after answering

### ISSUE THREAD

**Issue by aganders3** [chanzuckerberg/idetik#121]
This is a minor bug - the prototype will re-load the final task when it is answered. This is a result of the task advancing when answered.

**Comment by andy-sweet** [comment]
I think the more specific issue is that we always recreate and resubmit the task when answering, which always changes the task instance and triggers re-rendering/updating of the layers. While we also set the `taskIndex`, its value does not change, so does not cause any related re-renders or side-effects.
