### ISSUE TITLE
Add React and SDS to the existing example

### ISSUE THREAD

**Issue by aganders3** [chanzuckerberg/idetik#27]
The [existing example](https://github.com/chanzuckerberg/imaging-active-learning/blob/main/examples/index.html) uses the viewer library to display a mesh. We'd like to use React and SDS to develop the additional UI for the prototype application. The first step is changing the example to use these libraries. 

* Add React and SDS dependencies
* Connect the renderer to a canvas on a React-rendered page
* Use SDS to add a header component

**Comment by andy-sweet** [comment]
As we now have two examples, I'll leave those alone as plain typescript examples. Instead, I'll target creating a skeleton application for the prototype.
