### ISSUE TITLE
Support mock 2D cell tracking image data for prototype

### ISSUE THREAD

**Issue by andy-sweet** [chanzuckerberg/idetik#44]
All the mock data is publicly served over HTTP: https://public.czbiohub.org/royerlab/ultrack/multi-color/

The OME-Zarr image data only has one multi-scale level with dimensions: shape of {t:300, c:3, z:1, y:1440, x:1920} - i.e. it's a 2D time series of 3-channel images with a pixel dtype of uint8. Based on the [root group attributes](https://public.czbiohub.org/royerlab/ultrack/multi-color/image.zarr/.zattrs), the 3 channels are RGB (in that order).

The goal of this issue to write a new example that loads this image data. This can be dependent on #31 (i.e. we might want to solve that first) or will at least inform future completion of that more general issue.

**Comment by andy-sweet** [comment]
Given the omero metadata, we could pack this particular data into an RGB texture to get the desired outcome. But this might be a good time to add support for blending multiple image layers, and defining 3 layers from the same source, each with different channel indices. In the future, we could also imagine mapping each layer's value to its own colormap (that might not be red, green, and blue colormaps).

**Comment by aganders3** [comment]
I agree it may be a good opportunity to add blending. Perhaps it could be a single "MultichannelImageLayer" layer. This may make sense as the channels will presumably share the same data source. Restricting the blending to objects _within_ a layer may simplify the implementation.
