### ISSUE TITLE
Add Jest and implement basic unit tests for core components.

### ISSUE THREAD

**Issue by shlomnissan** [chanzuckerberg/idetik#5]

**Comment by aganders3** [comment]
I started looking into this. I'm planning to try vitest first, but will fall back to jest if there are issues or a strong preference for it.

I first need to understand the build system for this quasi-monorepo. I'm not sure the current config is correct. I think the `mode` arg is only ever `development` or `production`. @shlomnissan I think you modeled this after another repo - do you have a link? I'm confident I can figure it out, and will open a new issue if it becomes a bigger task.

```
# vite.config.js
export default defineConfig(({ mode }) => {
  if (mode === "lib") {
    console.log('Building library');
    return {
      plugins,
      build: {
        lib: {
          entry: path.resolve(__dirname, 'src/index.ts'),
          name: 'viz',
          fileName: (format) => `viz.${format}.js`,
        }
      },
    }
  } else {
    return {
      plugins,
      root: './examples',
      build: {
        outDir: 'dist',
      },
      resolve: {
        alias: {
          '@': path.resolve(__dirname, 'src'),
        },
      },
      server: {
        watch: {
          include: path.resolve(__dirname, 'src/**'),
        },
      },
    };
  }
});
```

**Comment by shlomnissan** [comment]
- I don’t have an opinion about vitest vs. jest. I had never heard of vitest before, but it looks fine!
- Having an “examples” folder in a library repo is pretty standard (see deck.gl, three.js, etc). I’m not sure I’d consider it a monorepo since the examples are not distinct projects.
- I thought `mode` was just an env variable. I didn’t model it after another repo. I just looked for a way to pass a variable to determine what type of build to generate. You can run `npx vite build --mode=lib` to build the library (I should have added a script for it.)
- If we’re not comfortable with this configuration, or if it conflicts with setting up vitest, we can simplify it. Since we’re not building a library right now, we can remove the `mode === "lib"` branch and just return whatever’s in the else statement.
