### ISSUE TITLE
Disable direct merge to the main branch. Block PRs that don't have at least approval. Add a PR summary template.

### ISSUE THREAD

**Issue by shlomnissan** [chanzuckerberg/idetik#9]

**Comment by andy-sweet** [comment]
@aganders3 had already set up the `Protect Main` rule set with the following settings enable

- Restrict deletions
- Require linear history
- Block force pushes

I edited that existing ruleset by adding `Require a pull request before merging` with 1 approval needed.

**Comment by andy-sweet** [comment]
Looks like someone else also configured PRs to squash merge with the PR title + description being used for the squashed commit message. This is my preferred option, so leaving that one alone.

**Comment by andy-sweet** [comment]
@shlomnissan : do you have any preferences or suggestions for a PR template?

For this project (which is still very much in the prototype phase), I'd like to keep this light. At a minimum probably a `Closes #...` line to remind people to link and auto-close relevant issues, followed by a description. I also don't mind adding sub-sections like `Motivation` to remind authors to explain why they are making this change.

**Comment by shlomnissan** [comment]
I don’t have any preference. I agree that we need to keep this light.

This is a structure I used in the past, but I'm not strongly attached to it:

```
### Summary
<!---
  Please try to cover the following questions in your summary:
  1. Describe the product (or technical) problem you are solving.
  2. Explain the engineering solution you have chosen.
  3. Discuss the implementation choices/tradeoffs you have made.
-->

### Related Issue
Closes #<issue-number>

### Tests & Checks
<!---
  How did you validate that your changes were implemented correctly?
  
  Please think about the following prompts:
  1. I wrote automated tests.
  2. I manually tested my changes, but I want to keep the details secret.
  3. I manually tested my changes, and here's what I did:
-->
```

**Comment by andy-sweet** [comment]
Looks good to me, though I'll remove the `secret details` example.

PR incoming.

**Comment by andy-sweet** [comment]
I also tested the branch protection rules by trying to push directly to main and got the resulting failure.

```shell
~/src/imaging-active-learning main
❯ git commit --allow-empty
[main 8271b5f] Testing main protection with empty commit

~/src/imaging-active-learning main ⇡ 11s
❯ git push                
Enumerating objects: 1, done.
Counting objects: 100% (1/1), done.
Writing objects: 100% (1/1), 212 bytes | 212.00 KiB/s, done.
Total 1 (delta 0), reused 0 (delta 0), pack-reused 0
remote: error: GH013: Repository rule violations found for refs/heads/main.
remote: Review all repository rules at http://github.com/chanzuckerberg/imaging-active-learning/rules?ref=refs%2Fheads%2Fmain
remote: 
remote: - Changes must be made through a pull request.
remote: 
To github.com:chanzuckerberg/imaging-active-learning.git
 ! [remote rejected] main -> main (push declined due to repository rule violations)
error: failed to push some refs to 'github.com:chanzuckerberg/imaging-active-learning.git'
```
